name: Deploy MacaeTempo App to Azure

# Aciona o workflow em cada push para a branch 'main'
on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite acionar manualmente também

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usará uma máquina virtual Linux para executar os passos

    steps:
      # 1. Clona o seu repositório para a máquina virtual
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      # 2. Configura o ambiente Node.js
      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Use a mesma versão que você configurou na Azure

      # 3. Instala as dependências e constrói o projeto
      - name: "Install Dependencies and Build"
        run: |
          npm install
          npm run build

      # 4. Faz o deploy para o Serviço de Aplicativo da Azure
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "macae-tempo" # <-- TROQUE pelo nome do seu App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Usa o segredo que configuramos
          package: . # Implanta o diretório atual (que contém .next, node_modules, etc.)
