name: Build and Deploy Next.js App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o seu repositório para a máquina virtual
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      # 2. Faz o deploy para o Serviço de Aplicativo da Azure
      # A própria Azure se encarregará de instalar as dependências e construir o projeto.
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "macae-tempo" # Nome do seu App Service na Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Usa o segredo que configuramos
          # A opção 'package' é omitida para que a action envie o código fonte,
          # ativando o build automático na Azure (Oryx).
